import { createClient } from '@supabase/supabase-js';
import dotenv from 'dotenv';
import fs from 'fs';
dotenv.config({ path: '.env.local' });
dotenv.config({ path: '.env' });

const s = createClient(process.env.VITE_SUPABASE_URL, process.env.VITE_SUPABASE_SERVICE_ROLE_KEY || process.env.SUPABASE_SERVICE_ROLE_KEY);

async function run() {
    // 1. Run the Trigger update SQL
    const sql = fs.readFileSync('fix_production_qty.sql', 'utf-8');
    const stmts = sql
        .split(';')
        .map(x => x.trim())
        .filter(x => x.length > 5 && !x.startsWith('--'));

    for (const stmt of stmts) {
        console.log('Running:', stmt.slice(0, 80).replace(/\n/g, ' '));
        const { error } = await s.rpc('execute_sql', { query: stmt });
        if (error) {
            console.error('  ERROR:', error.message);
        } else {
            console.log('  OK');
        }
    }

    // 2. Clear out T1.2 records generated by the bad DB trigger TODAY
    // The api inserts 1 row for Lane 1, 1 for Lane 2. 
    // The previous trigger added 2 rows EACH TIME to stock_ledger_v2 (total 4 rows per pulse).
    // We will delete all T1.2 ledger entries from today, and then re-insert them correctly from V1 log!
    console.log("Re-inserting correct ledger entries for T1.2 today...");
    const today = new Date().toISOString().slice(0, 10);

    // First find all V1 logging rows from T1.2 today
    const { data: v1Logs } = await s.from('production_logs')
        .select('*')
        .eq('machine_id', 'T1.2-M01')
        .gte('created_at', today);

    if (v1Logs && v1Logs.length > 0) {
        const v1Ids = v1Logs.map(l => l.id);

        // Delete the bad ledger entries
        const { error: delErr } = await s.from('stock_ledger_v2')
            .delete()
            .in('ref_doc', v1Ids);

        console.log("Deleted old bad ledger rows.", delErr || '');

        // Prepare correct ledger entries using the NEW.alarm_count logic AND new yield.
        // Lane1 yield should be 2, Lane2 should be 4.
        const inserts = [];
        for (const log of v1Logs) {
            let correctQty = 1;
            if (log.lane_id === 'Lane1') correctQty = 2;
            if (log.lane_id === 'Lane2') correctQty = 4;

            // Also update V1 log itself so it matches the correct yield
            // Note: API inserted alarm_count = 1 previously because yield was 1
            await s.from('production_logs').update({ alarm_count: correctQty }).eq('id', log.id);

            // Also update the UI V2 log correctly
            // V2 logs have the same created_at and same sku essentially but different log_id
            await s.from('production_logs_v2')
                .update({ output_qty: correctQty })
                .eq('machine_id', 'T1.2-M01')
                .eq('sku', log.product_sku)
                .eq('note', `Auto-logged from Lane: ${log.lane_id}`)
                // match timestamp roughly
                .gte('created_at', new Date(new Date(log.created_at).getTime() - 2000).toISOString())
                .lte('created_at', new Date(new Date(log.created_at).getTime() + 2000).toISOString());

            inserts.push({
                sku: log.product_sku,
                change_qty: correctQty,
                event_type: 'Production',
                ref_doc: log.id,
                notes: 'Auto-Log: ' + log.machine_id,
                timestamp: log.created_at
            });
        }

        const { error: insErr } = await s.from('stock_ledger_v2').insert(inserts);
        console.log("Inserted correct ledger rows.", insErr || '');
    }
}
run();
