const { createClient } = require('@supabase/supabase-js');
require('dotenv').config({ path: '../.env' });

const supabase = createClient(process.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL, process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.VITE_SUPABASE_SERVICE_ROLE_KEY);

async function checkValidDeliveries() {
    // 1. Deliveries generated by V6 trigger (Order Delivered) today
    const { data: logs } = await supabase
        .from('stock_ledger_v2')
        .select('*')
        .gte('timestamp', '2026-04-27T16:00:00+00:00') // MYT 28th 00:00:00
        .eq('event_type', 'Transfer Out')
        .like('notes', '%Order Delivered%');
        
    console.log(`Today (28th) there are ${logs.length} valid delivery deduction items.`);
    
    // Check if any ghost records were generated in the last 10 minutes
    const tenMinsAgo = new Date(Date.now() - 10 * 60000).toISOString();
    const { data: ghosts } = await supabase
        .from('stock_ledger_v2')
        .select('*')
        .gte('timestamp', tenMinsAgo)
        .like('notes', '%Order Created%');
        
    console.log(`Ghosts created in last 10 mins: ${ghosts.length}`);
}

checkValidDeliveries();
