import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = 'https://kdahubyhwndgyloaljak.supabase.co';
const SUPABASE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtkYWh1Ynlod25kZ3lsb2FsamFrIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2NTM4Njg4OSwiZXhwIjoyMDgwOTYyODg5fQ.82VCH3EqJXXfdR08i_pxr7yafb1gNunLd6wEomRcfVM';

const supabase = createClient(SUPABASE_URL, SUPABASE_KEY);

const initRows = [
    { role_name: 'Admin', page_id: 'profile', allowed: true },
    { role_name: 'Admin', page_id: 'construction', allowed: true },
    { role_name: 'Admin', page_id: 'factory-live-os', allowed: true },
    { role_name: 'Admin', page_id: 'dashboard', allowed: true },
    { role_name: 'Admin', page_id: 'data-v2', allowed: true },
    { role_name: 'Admin', page_id: 'customer-import', allowed: true },
    { role_name: 'Admin', page_id: 'universal-intake', allowed: true },
    { role_name: 'Admin', page_id: 'scanner', allowed: true },
    { role_name: 'Admin', page_id: 'jobs', allowed: true },
    { role_name: 'Admin', page_id: 'livestock', allowed: true },
    { role_name: 'Admin', page_id: 'inventory', allowed: true },
    { role_name: 'Admin', page_id: 'recipes', allowed: true },
    { role_name: 'Admin', page_id: 'products', allowed: true },
    { role_name: 'Admin', page_id: 'delivery', allowed: true },
    { role_name: 'Admin', page_id: 'order-summary', allowed: true },
    { role_name: 'Admin', page_id: 'dispatch', allowed: true },
    { role_name: 'Admin', page_id: 'production', allowed: true },
    { role_name: 'Admin', page_id: 'report-history', allowed: true },
    { role_name: 'Admin', page_id: 'users', allowed: true },
    { role_name: 'Admin', page_id: 'hr', allowed: true },
    { role_name: 'Admin', page_id: 'simple-stock', allowed: true },
    { role_name: 'Admin', page_id: 'maintenance', allowed: true },
    { role_name: 'Admin', page_id: 'lorry-management', allowed: true },
    { role_name: 'Admin', page_id: 'iot', allowed: true },
    { role_name: 'Admin', page_id: 'driver-management', allowed: true },
    { role_name: 'Admin', page_id: 'operators', allowed: true },
    { role_name: 'Admin', page_id: 'dev-log', allowed: true },
    { role_name: 'Admin', page_id: 'leave-calendar', allowed: true },
    { role_name: 'Admin', page_id: 'personal-report', allowed: true },
    { role_name: 'Admin', page_id: 'machine-schedule', allowed: true },
    { role_name: 'Admin', page_id: 'activity-logs', allowed: true },
    { role_name: 'Admin', page_id: 'stock-movement', allowed: true },
    { role_name: 'Admin', page_id: 'stock-audit', allowed: true },
    { role_name: 'Admin', page_id: 'audit-report', allowed: true },
    { role_name: 'Admin', page_id: 'reports', allowed: true },
    { role_name: 'Admin', page_id: 'notes', allowed: true },
    { role_name: 'Admin', page_id: 'tasks', allowed: true },
    { role_name: 'Admin', page_id: 'sop-center', allowed: true },
    { role_name: 'Admin', page_id: 'work-photos', allowed: true },
    { role_name: 'Admin', page_id: 'executive-reports', allowed: true },
    { role_name: 'Manager', page_id: 'profile', allowed: true },
    { role_name: 'Manager', page_id: 'construction', allowed: true },
    { role_name: 'Manager', page_id: 'factory-live-os', allowed: true },
    { role_name: 'Manager', page_id: 'dashboard', allowed: true },
    { role_name: 'Manager', page_id: 'data-v2', allowed: true },
    { role_name: 'Manager', page_id: 'customer-import', allowed: true },
    { role_name: 'Manager', page_id: 'universal-intake', allowed: true },
    { role_name: 'Manager', page_id: 'jobs', allowed: true },
    { role_name: 'Manager', page_id: 'livestock', allowed: true },
    { role_name: 'Manager', page_id: 'inventory', allowed: true },
    { role_name: 'Manager', page_id: 'recipes', allowed: true },
    { role_name: 'Manager', page_id: 'products', allowed: true },
    { role_name: 'Manager', page_id: 'delivery', allowed: true },
    { role_name: 'Manager', page_id: 'order-summary', allowed: true },
    { role_name: 'Manager', page_id: 'dispatch', allowed: true },
    { role_name: 'Manager', page_id: 'production', allowed: true },
    { role_name: 'Manager', page_id: 'report-history', allowed: true },
    { role_name: 'Manager', page_id: 'hr', allowed: true },
    { role_name: 'Manager', page_id: 'simple-stock', allowed: true },
    { role_name: 'Manager', page_id: 'maintenance', allowed: true },
    { role_name: 'Manager', page_id: 'lorry-management', allowed: true },
    { role_name: 'Manager', page_id: 'iot', allowed: true },
    { role_name: 'Manager', page_id: 'driver-management', allowed: true },
    { role_name: 'Manager', page_id: 'operators', allowed: true },
    { role_name: 'Manager', page_id: 'leave-calendar', allowed: true },
    { role_name: 'Manager', page_id: 'personal-report', allowed: true },
    { role_name: 'Manager', page_id: 'machine-schedule', allowed: true },
    { role_name: 'Manager', page_id: 'activity-logs', allowed: true },
    { role_name: 'Manager', page_id: 'stock-movement', allowed: true },
    { role_name: 'Manager', page_id: 'stock-audit', allowed: true },
    { role_name: 'Manager', page_id: 'audit-report', allowed: true },
    { role_name: 'Manager', page_id: 'reports', allowed: true },
    { role_name: 'Manager', page_id: 'notes', allowed: true },
    { role_name: 'Manager', page_id: 'tasks', allowed: true },
    { role_name: 'Manager', page_id: 'sop-center', allowed: true },
    { role_name: 'Manager', page_id: 'work-photos', allowed: true },
    { role_name: 'Manager', page_id: 'executive-reports', allowed: true },
    { role_name: 'Driver', page_id: 'delivery-driver', allowed: true },
    { role_name: 'Driver', page_id: 'delivery-history', allowed: true },
    { role_name: 'Driver', page_id: 'leave-calendar', allowed: true },
    { role_name: 'Driver', page_id: 'lorry-service', allowed: true },
    { role_name: 'Driver', page_id: 'profile', allowed: true },
    { role_name: 'Driver', page_id: 'personal-report', allowed: true },
    { role_name: 'Driver', page_id: 'activity-logs', allowed: true },
    { role_name: 'Operator', page_id: 'scanner', allowed: true },
    { role_name: 'Operator', page_id: 'leave-calendar', allowed: true },
    { role_name: 'Operator', page_id: 'profile', allowed: true },
    { role_name: 'Operator', page_id: 'personal-report', allowed: true },
    { role_name: 'Operator', page_id: 'activity-logs', allowed: true },
    { role_name: 'HR', page_id: 'profile', allowed: true },
    { role_name: 'HR', page_id: 'hr', allowed: true },
    { role_name: 'HR', page_id: 'leave-calendar', allowed: true },
    { role_name: 'HR', page_id: 'notes', allowed: true },
    { role_name: 'HR', page_id: 'tasks', allowed: true },
    { role_name: 'HR', page_id: 'personal-report', allowed: true },
    { role_name: 'HR', page_id: 'activity-logs', allowed: true }
]; // EXCLUDES Device!

async function run() {
    console.log("Emptying old roles");
    const ALL_ROLES = ['Admin', 'Manager', 'HR', 'Operator', 'Driver'];
    await supabase.from('role_permissions').delete().in('role_name', ALL_ROLES);

    console.log("Inserting init roles");
    const { data: d2, error: e2 } = await supabase.from('role_permissions').insert(initRows);
    console.log("Insert ok:", !e2, e2);
}
run();
